### ISSUE TITLE
all_ppls

### ISSUE THREAD

**Issue by borgr** [xiamengzhou/training_trajectory_analysis#2]
Is it possible something is missing from the data?
I find all_others, scores and steps but not all ppl, and things seem to look for it.
for example this:
```all_ppls = torch.load(f"data/trend_of_tokens/all_ppls-{dataset_name}.pt")```

**Comment by xiamengzhou** [comment]
Yeah it seems to be missing. But you should be able to get `all_ppls` via `exp(-all_scores)`! Hope it helps!

**Comment by borgr** [comment]
Added PR #3 with commit [e2187d9](https://github.com/xiamengzhou/training_trajectory_analysis/pull/3/commits/e2187d93670bc6632f736ee6282707fe54f82619)

**Comment by xiamengzhou** [comment]
Thanks!
